# Generated by Django 5.0.6 on 2026-08-13 04:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=200)),
                ("consigne", models.TextField(blank=True)),
                ("genere_par_ia", models.BooleanField(default=False)),
                ("publie", models.BooleanField(default=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "classe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quizzes",
                        to="academics.classe",
                    ),
                ),
                (
                    "professeur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quizzes_crees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Contrôle / Quiz",
                "verbose_name_plural": "Contrôles / Quiz",
                "ordering": ["-date_creation"],
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ordre", models.PositiveIntegerField(default=0)),
                ("enonce", models.TextField()),
                (
                    "choix",
                    models.JSONField(
                        default=list, help_text="Liste des choix proposés"
                    ),
                ),
                ("index_bonne_reponse", models.PositiveSmallIntegerField()),
                ("explication", models.TextField(blank=True)),
                ("points", models.PositiveIntegerField(default=2)),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="quizzes.quiz",
                    ),
                ),
            ],
            options={
                "ordering": ["ordre", "id"],
            },
        ),
        migrations.CreateModel(
            name="Tentative",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_soumission", models.DateTimeField(auto_now_add=True)),
                ("score", models.FloatField(default=0)),
                ("score_max", models.FloatField(default=0)),
                (
                    "eleve",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tentatives_quiz",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tentatives",
                        to="quizzes.quiz",
                    ),
                ),
            ],
            options={
                "ordering": ["-date_soumission"],
                "unique_together": {("quiz", "eleve")},
            },
        ),
        migrations.CreateModel(
            name="ReponseEleve",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "index_choisi",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reponses_eleves",
                        to="quizzes.question",
                    ),
                ),
                (
                    "tentative",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reponses",
                        to="quizzes.tentative",
                    ),
                ),
            ],
        ),
    ]
