# Generated by Django 5.0.6 on 2026-08-13 04:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Devoir",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=200)),
                ("enonce", models.TextField()),
                ("bareme_points", models.PositiveIntegerField(default=20)),
                ("date_limite", models.DateTimeField(blank=True, null=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "classe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devoirs",
                        to="academics.classe",
                    ),
                ),
                (
                    "professeur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devoirs_crees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date_creation"],
            },
        ),
        migrations.CreateModel(
            name="Copie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reponse_texte", models.TextField(blank=True)),
                (
                    "fichier",
                    models.FileField(blank=True, null=True, upload_to="copies/%Y/%m/"),
                ),
                ("date_rendu", models.DateTimeField(auto_now_add=True)),
                ("note", models.FloatField(blank=True, null=True)),
                ("appreciation_generale", models.TextField(blank=True)),
                ("points_forts", models.JSONField(blank=True, default=list)),
                ("points_a_ameliorer", models.JSONField(blank=True, default=list)),
                ("correction_detaillee", models.TextField(blank=True)),
                ("corrigee_par_ia", models.BooleanField(default=False)),
                ("validee_par_professeur", models.BooleanField(default=False)),
                (
                    "eleve",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="copies_rendues",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "devoir",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="copies",
                        to="homework.devoir",
                    ),
                ),
            ],
            options={
                "ordering": ["-date_rendu"],
                "unique_together": {("devoir", "eleve")},
            },
        ),
    ]
