# Generated by Django 5.0.6 on 2026-08-13 04:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Classe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        help_text="Ex : 3AM 2, Terminale Sciences B...", max_length=100
                    ),
                ),
                (
                    "cycle",
                    models.CharField(
                        choices=[
                            ("primaire", "Primaire"),
                            ("moyen", "Moyen (CEM)"),
                            ("secondaire", "Secondaire (Lycée)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "annee",
                    models.CharField(
                        choices=[
                            ("1AP", "1ère année primaire"),
                            ("2AP", "2ème année primaire"),
                            ("3AP", "3ème année primaire"),
                            ("4AP", "4ème année primaire"),
                            ("5AP", "5ème année primaire"),
                            ("1AM", "1ère année moyenne"),
                            ("2AM", "2ème année moyenne"),
                            ("3AM", "3ème année moyenne"),
                            ("4AM", "4ème année moyenne (BEM)"),
                            ("1AS", "1ère année secondaire"),
                            ("2AS", "2ème année secondaire"),
                            ("3AS", "3ème année secondaire (Baccalauréat)"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "filiere",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("tc_sciences", "Tronc commun Sciences"),
                            ("tc_lettres", "Tronc commun Lettres"),
                            ("sciences_exp", "Sciences expérimentales"),
                            ("mathematiques", "Mathématiques"),
                            ("techniques_math", "Techniques mathématiques"),
                            ("gestion_eco", "Gestion et économie"),
                            ("lettres_philo", "Lettres et philosophie"),
                            ("lettres_langues", "Lettres et langues étrangères"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "matiere",
                    models.CharField(
                        help_text="Matière du programme national algérien",
                        max_length=150,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "code_acces",
                    models.CharField(editable=False, max_length=8, unique=True),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "eleves",
                    models.ManyToManyField(
                        blank=True,
                        limit_choices_to={"role": "eleve"},
                        related_name="classes_suivies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "professeur",
                    models.ForeignKey(
                        limit_choices_to={"role": "professeur"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classes_enseignees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date_creation"],
            },
        ),
    ]
