# Generated by Django 5.0.6 on 2026-08-13 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Classe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        help_text="Ex : Terminale S1, CM2 B...", max_length=100
                    ),
                ),
                (
                    "matiere",
                    models.CharField(
                        help_text="Ex : Mathématiques, Histoire-Géographie...",
                        max_length=100,
                    ),
                ),
                ("niveau", models.CharField(blank=True, max_length=50)),
                ("description", models.TextField(blank=True)),
                (
                    "code_acces",
                    models.CharField(editable=False, max_length=8, unique=True),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-date_creation"],
            },
        ),
    ]
