# Generated by Django 5.0.6 on 2026-08-13 04:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="classe",
            name="eleves",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"role": "eleve"},
                related_name="classes_suivies",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="classe",
            name="professeur",
            field=models.ForeignKey(
                limit_choices_to={"role": "professeur"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="classes_enseignees",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
