# Generated by Django 5.0.6 on 2026-08-13 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents_perso", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dossier",
            name="couleur",
            field=models.CharField(
                choices=[
                    ("#2563eb", "Bleu"),
                    ("#16a34a", "Vert"),
                    ("#d97706", "Orange"),
                    ("#dc2626", "Rouge"),
                    ("#7c3aed", "Violet"),
                    ("#0891b2", "Cyan"),
                    ("#be185d", "Rose"),
                    ("#4b5563", "Gris"),
                ],
                default="#2563eb",
                max_length=7,
            ),
        ),
    ]
