# Generated by Django 5.0.6 on 2026-08-13 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="utilisateur",
            name="client_depuis_le",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="utilisateur",
            name="generations_ia_mois_courant",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="utilisateur",
            name="generations_ia_mois_reference",
            field=models.CharField(
                blank=True, help_text="Format AAAA-MM", max_length=7
            ),
        ),
    ]
