# Generated by Django 5.0.6 on 2026-08-13 05:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_utilisateur_client_depuis_le_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="utilisateur",
            name="code_famille",
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="utilisateur",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Administrateur"),
                    ("professeur", "Professeur"),
                    ("eleve", "Élève"),
                    ("parent", "Parent"),
                ],
                default="eleve",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="LienParentEleve",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "eleve",
                    models.ForeignKey(
                        limit_choices_to={"role": "eleve"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="liens_parents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        limit_choices_to={"role": "parent"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="liens_enfants",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("parent", "eleve")},
            },
        ),
    ]
